### PR TITLE
Adds check for volume creation status

### PR DESCRIPTION
**Pull request by e0d**
This pull ensures that newly created volumes are in the available status before attempting to attach them, which results in an error.

```
Traceback (most recent call last):
  File "./raidformer.py", line 168, in <module>
    ec2conn.attach_volume(vol.id, instance_data['instance-id'], device)
  File "/usr/lib/python2.7/dist-packages/boto/ec2/connection.py", line 1369, in attach_volume
    return self.get_status('AttachVolume', params, verb='POST')
  File "/usr/lib/python2.7/dist-packages/boto/connection.py", line 935, in get_status
    raise self.ResponseError(response.status, response.reason, body)
boto.exception.EC2ResponseError: EC2ResponseError: 400 Bad Request
<?xml version="1.0" encoding="UTF-8"?>
<Response><Errors><Error><Code>IncorrectState</Code><Message>vol-c92fa384 is not 'available'.</Message></Error></Errors><RequestID>97f9ecf4-1b41-4c58-8254-63fc725057c8</RequestID></Response>
```

### CODE REVIEW

**Comment by jsmartin** [comment]
Thanks for the pull request. One quick change:

```
print "Volume {volume} is available".format(volume=vol.id)
```

For consistency's sake, can you please make that similar to all of the other print statements (using %s).

Thanks!

**Comment by jlafon** [comment]
I am seeing the same issue, which is resolved when using this branch.

**Comment by e0d** [comment]
@jsmartin Anything else you would like me to do for this PR?

**Comment by jsmartin** [comment]
Thanks!

**Pull request merged**
